apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: r5o-cluster-01
  region: us-east-2
  version: "1.19"

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 40
