apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: r5o-cluster-k8s
  region: us-east-2
  version: "1.19"

nodeGroups:
  - name: ng-1
    instanceType: m5.xlarge
    desiredCapacity: 2
    privateNetworking: true
    amiFamily: Ubuntu2004
    volumeSize: 40
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::517533378855:policy/emr-job-execution-policy
