from datetime import date, timedelta
import os

from pyspark.sql.types import (
    IntegerType, StringType, StructType, StructField, TimestampType
)

S3_PREFIX = os.environ['S3_PREFIX']
_default_date = date.today() - timedelta(days=1)
S3_SUFFIX = os.environ.get('S3_SUFFIX',
                           f"rh_{_default_date.strftime('%Y%m%d')}.gz")

DS_CONFIG = [
    {
        'input': f"{S3_PREFIX}_allergy_{S3_SUFFIX}",
        'output': 'public.stage_allergy',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('type', StringType(), nullable=True),
            StructField('description', StringType(), nullable=True),
            StructField('onset_date', StringType(), nullable=True),
            StructField('resolved_date', StringType(), nullable=True),
            StructField('severity', StringType(), nullable=True),
            StructField('reaction_code', StringType(), nullable=True),
            StructField('reaction', StringType(), nullable=True),
            StructField('product_code', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_demographic_{S3_SUFFIX}",
        'output': 'public.stage_demographic',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('client_patient_id', StringType(), nullable=True),
            StructField('first_name', StringType(), nullable=True),
            StructField('middle_name', StringType(), nullable=True),
            StructField('last_name', StringType(), nullable=True),
            StructField('prefix', StringType(), nullable=True),
            StructField('suffix', StringType(), nullable=True),
            StructField('ssn', StringType(), nullable=True),
            StructField('dob', StringType(), nullable=True),
            StructField('other_id', StringType(), nullable=True),
            StructField('account_id', StringType(), nullable=True),
            StructField('gender', StringType(), nullable=True),
            StructField('race', StringType(), nullable=True),
            StructField('ethnicity', StringType(), nullable=True),
            StructField('primary_language', StringType(), nullable=True),
            StructField('phone_number', StringType(), nullable=True),
            StructField('phone_ext', StringType(), nullable=True),
            StructField('phone_type', StringType(), nullable=True),
            StructField('second_number', StringType(), nullable=True),
            StructField('second_ext', StringType(), nullable=True),
            StructField('second_type', StringType(), nullable=True),
            StructField('first_email', StringType(), nullable=True),
            StructField('second_email', StringType(), nullable=True),
            StructField('death_indication', StringType(), nullable=True),
            StructField('death_date', StringType(), nullable=True),
            StructField('address_type', StringType(), nullable=True),
            StructField('address_line_1', StringType(), nullable=True),
            StructField('address_line_2', StringType(), nullable=True),
            StructField('city', StringType(), nullable=True),
            StructField('state', StringType(), nullable=True),
            StructField('zip', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_diagnosis_{S3_SUFFIX}",
        'output': 'public.stage_diagnosis',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('icd9_code', StringType(), nullable=True),
            StructField('icd10_code', StringType(), nullable=True),
            StructField('loinc_code', StringType(), nullable=True),
            StructField('snomed_code', StringType(), nullable=True),
            StructField('description', StringType(), nullable=True),
            StructField('diagnosed_date', StringType(), nullable=True),
            StructField('resolved_date', StringType(), nullable=True),
            StructField('status', StringType(), nullable=True),
            StructField('severity', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_encounter_{S3_SUFFIX}",
        'output': 'public.stage_encounter',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('encounter_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('encounter_type', StringType(), nullable=True),
            StructField('encounter_date', StringType(), nullable=True),
            StructField('encounter_time', StringType(), nullable=True),
            StructField('clinician', StringType(), nullable=True),
            StructField('member_subscriber_id', StringType(), nullable=True),
            StructField('insurance_type', StringType(), nullable=True),
            StructField('status', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_immunization_{S3_SUFFIX}",
        'output': 'public.stage_immunization',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('service_date', StringType(), nullable=True),
            StructField('cpt_code', StringType(), nullable=True),
            StructField('cvx_code', StringType(), nullable=True),
            StructField('description', StringType(), nullable=True),
            StructField('dose', StringType(), nullable=True),
            StructField('units', StringType(), nullable=True),
            StructField('route_code', StringType(), nullable=True),
            StructField('route_description', StringType(), nullable=True),
            StructField('clinician', StringType(), nullable=True),
            StructField('exception_reason_code', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_lab_result_{S3_SUFFIX}",
        'output': 'public.stage_lab_result',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('service_code', StringType(), nullable=True),
            StructField('service_description', StringType(), nullable=True),
            StructField('provider_id', StringType(), nullable=True),
            StructField('provider_name', StringType(), nullable=True),
            StructField('service_coding_system_name', StringType(), nullable=True),
            StructField('result_date', StringType(), nullable=True),
            StructField('observation_description', StringType(), nullable=True),
            StructField('observation_coding_system', StringType(), nullable=True),
            StructField('status', StringType(), nullable=True),
            StructField('code', StringType(), nullable=True),
            StructField('value', StringType(), nullable=True),
            StructField('units', StringType(), nullable=True),
            StructField('ref_range', StringType(), nullable=True),
            StructField('original_code', StringType(), nullable=True),
            StructField('order_date', StringType(), nullable=True),
            StructField('collection_date', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_medication_{S3_SUFFIX}",
        'output': 'public.stage_medication',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('id_ndc', StringType(), nullable=True),
            StructField('id_rxnorm', StringType(), nullable=True),
            StructField('name', StringType(), nullable=True),
            StructField('dose', StringType(), nullable=True),
            StructField('form', StringType(), nullable=True),
            StructField('route', StringType(), nullable=True),
            StructField('sig_code', StringType(), nullable=True),
            StructField('sig', StringType(), nullable=True),
            StructField('duration', StringType(), nullable=True),
            StructField('frequency', StringType(), nullable=True),
            StructField('start_date', StringType(), nullable=True),
            StructField('stop_date', StringType(), nullable=True),
            StructField('quantity', StringType(), nullable=True),
            StructField('prescribed_npi', StringType(), nullable=True),
            StructField('status', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_medsurg_history_{S3_SUFFIX}",
        'output': 'public.stage_medsurg',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('date', StringType(), nullable=True),
            StructField('code', StringType(), nullable=True),
            StructField('description', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_procedure_{S3_SUFFIX}",
        'output': 'public.stage_procedure',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('cpt4_hcpcs_code', StringType(), nullable=True),
            StructField('description', StringType(), nullable=True),
            StructField('date', StringType(), nullable=True),
            StructField('modifier_code1', StringType(), nullable=True),
            StructField('modifier_code2', StringType(), nullable=True),
            StructField('modifier_code3', StringType(), nullable=True),
            StructField('modifier_code4', StringType(), nullable=True),
            StructField('ordered_by_clinician', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_quality_data_{S3_SUFFIX}",
        'output': 'public.stage_quality_data',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('item_name', StringType(), nullable=True),
            StructField('value', StringType(), nullable=True),
            StructField('observation_date', StringType(), nullable=True),
            StructField('code', StringType(), nullable=True),
            StructField('code_type', StringType(), nullable=True),
            StructField('emr_section', StringType(), nullable=True),
            StructField('recorded_elsewhere_within_extracts', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_social_history_{S3_SUFFIX}",
        'output': 'public.stage_social_history',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('observation_date', StringType(), nullable=True),
            StructField('smoking_status', StringType(), nullable=True),
            StructField('marital_status', StringType(), nullable=True),
            StructField('employment_status', StringType(), nullable=True),
            StructField('transportation', StringType(), nullable=True),
            StructField('living_arrangement', StringType(), nullable=True),
            StructField('alcohol_user', StringType(), nullable=True),
            StructField('drug_user', StringType(), nullable=True),
            StructField('caffeine_user', StringType(), nullable=True),
            StructField('sexually_active', StringType(), nullable=True),
            StructField('exercise_hours_week', StringType(), nullable=True),
            StructField('education_level', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_vitals_{S3_SUFFIX}",
        'output': 'public.stage_vital',
        'schema': StructType([
            StructField('client_id', StringType(), nullable=True),
            StructField('patient_id', StringType(), nullable=True),
            StructField('service_date', StringType(), nullable=True),
            StructField('service_time', StringType(), nullable=True),
            StructField('height_cm', StringType(), nullable=True),
            StructField('height_in', StringType(), nullable=True),
            StructField('weight_kg', StringType(), nullable=True),
            StructField('weight_lbs', StringType(), nullable=True),
            StructField('temperature_c', StringType(), nullable=True),
            StructField('temperature_f', StringType(), nullable=True),
            StructField('pulse', StringType(), nullable=True),
            StructField('respiration', StringType(), nullable=True),
            StructField('bp_systolic', StringType(), nullable=True),
            StructField('bp_diastolic', StringType(), nullable=True),
            StructField('oxygen_saturation', StringType(), nullable=True),
            StructField('bmi', StringType(), nullable=True),
            StructField('encounter_id', StringType(), nullable=True),
        ]),
    },
    {
        'input': f"{S3_PREFIX}_extraction_summary_{S3_SUFFIX}",
        'output': 'public.extraction_summary',
        'schema': StructType([
            StructField('object', StringType(), nullable=True),
            StructField('client_id', StringType(), nullable=True),
            StructField('count', IntegerType(), nullable=True),
            StructField('extraction_date', TimestampType(), nullable=True),
        ]),
    },
]
