apiVersion: v1
kind: Pod
metadata:
  name: async-ingest
  namespace: default
  labels:
    name: async-ingest
    instance: async-ingest-pod
    version: "1.0.0"
    component: batch
    part-of: pods
spec:
  restartPolicy: Never  # Always
  containers:
    - name: async-ingest
      image: 517533378855.dkr.ecr.us-east-2.amazonaws.com/async-ingest:latest
      imagePullPolicy: Always  # IfNotPresent
      env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-client-secret
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-client-secret
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-client-secret
              key: AWS_DEFAULT_REGION
        - name: IAM_REDSHIFT
          valueFrom:
            secretKeyRef:
              name: aws-connect-secret
              key: IAM_REDSHIFT
        - name: REDSHIFT_DB_URL
          valueFrom:
            secretKeyRef:
              name: aws-connect-secret
              key: REDSHIFT_DB_URL
        - name: POSTGRES_DB_URL
          valueFrom:
            secretKeyRef:
              name: aws-connect-secret
              key: POSTGRES_DB_URL
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "4000m"
          memory: "1Gi"