apiVersion: v1
kind: Pod
metadata:
  name: smoke-test
  namespace: default
  labels:
    name: smoke-test
    instance: smoke-test-pod
    version: "1.0.0"
    component: batch
    part-of: pods
spec:
  restartPolicy: Never  # Always
  serviceAccountName: spark
  containers:
    - name: smoke-test
      image: my.docker.registry/spark-py:3.1.1-3.2
      imagePullPolicy: Always  # IfNotPresent
      args: [
        "/bin/sh",
        "-c",
        "/opt/spark/bin/spark-submit \
        --master k8s://https://123456789.lky7.us-east-2.eks.amazonaws.com:443 \
        --deploy-mode cluster \
        --name smoke-test \
        --conf spark.executor.instances=4 \
        --conf spark.executor.memory=2G \
        --conf spark.executor.cores=2 \
        --conf spark.kubernetes.namespace=default \
        --conf spark.kubernetes.container.image=my.docker.registry/spark-py:3.1.1-3.2 \
        --conf spark.kubernetes.container.image.pullPolicy=Always \ 
        --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
        --conf spark.kubernetes.executor.deleteOnTermination=false \
        --conf spark.jars.ivy=/tmp/.ivy \
        local:///opt/spark/examples/src/main/python/pi.py 100"
      ]
      resources:
        requests:
          cpu: "250m"
          memory: "500Mi"
        limits:
          cpu: "4000m"
          memory: "8Gi"