apiVersion: v1
kind: Pod
metadata:
  name: spark-ingest
  namespace: default
  labels:
    name: spark-ingest
    instance: spark-ingest-pod
    version: "1.0.0"
    component: batch
    part-of: pods
spec:
  restartPolicy: Never  # Always
  containers:
    - name: spark-ingest
      image: 517533378855.dkr.ecr.us-east-2.amazonaws.com/spark-py:3.1.1
      imagePullPolicy: Always  # IfNotPresent
      command: [
            "/bin/sh",
            "-c",
            "/opt/spark/bin/spark-submit \
            --master k8s://https://10.100.0.1:443 \
            --deploy-mode cluster \
            --name spark-ingest \
            --conf spark.executor.instances=2 \
            --conf spark.executor.memory=5G \
            --conf spark.executor.cores=2 \
            --conf spark.sql.shuffle.partitions=10 \
            --conf spark.kubernetes.container.image=517533378855.dkr.ecr.us-east-2.amazonaws.com/spark-ingest:latest \
            --conf spark.kubernetes.container.image.pullPolicy=Always \
            local:///opt/spark/spark-ingest/main.py \
            --filepath=\"/opt/spark/examples/src/main/python/pi.py\""
      ]
      env:
        - name: LOG_LEVEL
          value: "DEBUG"
      resources:
        requests:
          cpu: "500m"
          memory: "500Mi"
        limits:
          cpu: "4000m"
          memory: "1Gi"