apiVersion: v1
kind: Pod
metadata:
  name: spark-ingest
  namespace: default
  labels:
    name: spark-ingest
    instance: spark-ingest-pod
    version: "1.0.0"
    component: batch
    part-of: pods
spec:
  restartPolicy: Never  # Always
  serviceAccountName: spark
  containers:
    - name: spark-ingest
      image: 517533378855.dkr.ecr.us-east-2.amazonaws.com/spark-py:3.1.1
      imagePullPolicy: Always  # IfNotPresent
      command: [
        "/bin/sh",
        "-c",
        "/opt/spark/bin/spark-submit \
        --master k8s://https://91EA474523FB73BDEC46D06AEAA0A80D.sk1.us-east-2.eks.amazonaws.com:443 \
        --deploy-mode cluster \
        --name spark-ingest \
        --conf spark.executor.instances=2 \
        --conf spark.kubernetes.container.image=517533378855.dkr.ecr.us-east-2.amazonaws.com/spark-ingest:latest \
        --conf spark.kubernetes.authenticate.driver.serviceAccountName=spark \
        local:///opt/spark/spark-ingest/main.py"
      ]
