version: "3.8"
services:
  spark-ingest:
    image: spark-ingest-azure
    build:
      context: .
      dockerfile: Dockerfile-azure
    command: [
      "/bin/sh",
      "-c",
      "/opt/spark/bin/spark-submit \
      --name spark-ingest \
      local:///opt/spark/spark-ingest/main.py \
      --filepath wasbs://spark@airflowstoragesandbox.blob.core.windows.net/test/mnm_dataset.csv"
      ]
    env_file: .env
    environment:
      - LOG_LEVEL=DEBUG
